config/routes.rb
Rails.application.routes.draw do
  resources :calls

  resources :subscribers

  resources :user_files
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :subscriber

  scope :by_subscriber, lambda { |s| where(subscriber_id: s) }
  scope :before, lambda { |s| where('end_date <= ?', s) }
  scope :after, lambda { |s| where('start_date >= ?', s) }
  scope :between, lambda { |a, b| before(a).after(b) }
  scope :by_operator_name, lambda { |s| where('service like ?', "%#{s}%") } # operator_name: МТС, Билайн, Мегафон, гор

  class << self
    # Example: sum_cost_by_service
    def method_missing(meth, *args, &block)
      if meth.to_s =~ /^(sum|avg|min|max|count)_(#{column_names.join('|')})(?:_by_(#{column_names.join('|')}))?$/
        selector = select("#{$1}(#{$2}) as #{$2}").order($2)
        selector = selector.select($3).group($3) if $3.present?
        selector
      else
        super
      end
    end

    def phones
      pluck(:receiver).uniq
    end
  end

  class ActiveRecord_Relation
    def t
      header = select_values
      model_attrs = header.map { |x| x =~ /\S+\s+(\S+)\s*$/ ? $1 : x }
      values = to_a.map { |x| model_attrs.map { |h| x.read_attribute(h) } }
      max_length = []
      header.each_with_index { |x, i| max_length[i] = ([x.size]+values.map { |s| s[i].to_s.size }).max }

      line = '+'+max_length.map { |x| '-' * (x+2) }.join('+')+'+'
      cells = lambda do |row|
        '|'+row.map.with_index do |x, i|
          len = max_length[i]
          " #{x.to_s.send(x.is_a?(Fixnum) || x.is_a?(Float) ? :rjust : :ljust, len)} "
        end.join('|')+'|'
      end

      puts line
      puts cells.call(header)
      puts line
      values.each { |row| puts cells.call(row) }
      puts line
    end
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:subscriber, :call_date, :length, :length_r, :cost, :caller, :receiver, :action, :service, :service_type, :volume)
    end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subscriber %><br>
    <%= f.text_field :subscriber %>
  </div>
  <div class="field">
    <%= f.label :call_date %><br>
    <%= f.datetime_select :call_date %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.time_select :length %>
  </div>
  <div class="field">
    <%= f.label :length_r %><br>
    <%= f.number_field :length_r %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :caller %><br>
    <%= f.text_field :caller %>
  </div>
  <div class="field">
    <%= f.label :receiver %><br>
    <%= f.text_field :receiver %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :service %><br>
    <%= f.text_field :service %>
  </div>
  <div class="field">
    <%= f.label :service_type %><br>
    <%= f.text_field :service_type %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calls</h1>

<table>
  <thead>
    <tr>
      <th>Subscriber</th>
      <th>Call date</th>
      <th>Length</th>
      <th>Length r</th>
      <th>Cost</th>
      <th>Caller</th>
      <th>Receiver</th>
      <th>Action</th>
      <th>Service</th>
      <th>Service type</th>
      <th>Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.subscriber %></td>
        <td><%= call.call_date %></td>
        <td><%= call.length %></td>
        <td><%= call.length_r %></td>
        <td><%= call.cost %></td>
        <td><%= call.caller %></td>
        <td><%= call.receiver %></td>
        <td><%= call.action %></td>
        <td><%= call.service %></td>
        <td><%= call.service_type %></td>
        <td><%= call.volume %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New Call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subscriber:</strong>
  <%= @call.subscriber %>
</p>

<p>
  <strong>Call date:</strong>
  <%= @call.call_date %>
</p>

<p>
  <strong>Length:</strong>
  <%= @call.length %>
</p>

<p>
  <strong>Length r:</strong>
  <%= @call.length_r %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @call.cost %>
</p>

<p>
  <strong>Caller:</strong>
  <%= @call.caller %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @call.receiver %>
</p>

<p>
  <strong>Action:</strong>
  <%= @call.action %>
</p>

<p>
  <strong>Service:</strong>
  <%= @call.service %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @call.service_type %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @call.volume %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>